export const weekdaysname = () => {
  return [
    {
      day: "0",
      name: "Sun",
    },
    {
      day: "1",
      name: "Mon",
    },
    {
      day: "2",
      name: "Tue",
    },
    {
      day: "3",
      name: "Wed",
    },
    {
      day: "4",
      name: "Thu",
    },
    {
      day: "5",
      name: "Fri",
    },
    {
      day: "6",
      name: "Sat",
    },
  ];
};
export const weekdayshort = () => {
  return [
    {
      day: "0",
      name: "ST",
      name2: "S",
    },
    {
      day: "1",
      name: "MW",
      name2: "M",
    },
    {
      day: "2",
      name: "ST",
      name2: "T",
    },
    {
      day: "3",
      name: "MW",
      name2: "W",
    },
    {
      day: "4",
      name: "RA",
      name2: "R",
    },
    {
      day: "5",
      name: "Fri",
    },
    {
      day: "6",
      name: "RA",
      name2: "A",
    },
  ];
};
export const timeofday = () => {
  return [
    {
      day: "0",
      name: "Good Night",
    },
    {
      day: "1",
      name: "Good Night",
    },
    {
      day: "2",
      name: "Have a Good Night Sleep",
    },
    {
      day: "3",
      name: "Have a Good Night Sleep",
    },
    {
      day: "4",
      name: "Have a Good Night Sleep",
    },
    {
      day: "5",
      name: "Have a Good Night Sleep",
    },
    {
      day: "6",
      name: "Good Morning",
    },
    {
      day: "7",
      name: "Good Morning",
    },
    {
      day: "8",
      name: "Good Morning",
    },
    {
      day: "9",
      name: "Good Morning",
    },
    {
      day: "10",
      name: "Good Morning",
    },
    {
      day: "11",
      name: "Good Morning",
    },
    {
      day: "12",
      name: "Good Noon",
    },
    {
      day: "13",
      name: "Good Afternoon",
    },
    {
      day: "14",
      name: "Good Afternoon",
    },
    {
      day: "15",
      name: "Good Afternoon",
    },
    {
      day: "16",
      name: "Good Afternoon",
    },
    {
      day: "17",
      name: "Good Afternoon",
    },
    {
      day: "18",
      name: "Good Evening",
    },
    {
      day: "19",
      name: "Good Evening",
    },
    {
      day: "20",
      name: "Good Evening",
    },
    {
      day: "21",
      name: "Good Night",
    },
    {
      day: "22",
      name: "Good Night",
    },
    {
      day: "23",
      name: "Good Night",
    },
    {
      day: "24",
      name: "Good Night",
    },
  ];
};
export const sacroomsdata = () => {
  return [
    [
      {
        name: "SAC201",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC202",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC203",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC204",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC205",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC206",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC207",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC208",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC209",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC210",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC211",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC212",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC213",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC214",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
    ],
    [
      {
        name: "SAC301",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC302",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC303",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC304",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC305",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC306",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC307",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC308",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC309",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC310",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC311",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC312",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC313",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC314",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC315",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC316",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
    ],
    [
      {
        name: "SAC401",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC402",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC403",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC404",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC405",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC406",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC407",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC408",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC409",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC410",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC411",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC412",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC413",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC414",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC415",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC416",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC417",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
    ],
    [
      {
        name: "SAC501",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC502",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC503",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC504",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC505",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC506",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC507",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC508",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC509",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC510",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
    ],
    [
      {
        name: "SAC601",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC602",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC603",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC604",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC605",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC606",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC607",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC608",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC609",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC610",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC611",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
    ],
    [
      {
        name: "SAC922",
        faculty: "MjH1",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC928",
        faculty: "AIq",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC935",
        faculty: "RIH",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC942",
        faculty: "SfR1",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC947",
        faculty: "Rsf",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
      {
        name: "SAC955",
        faculty: "ZBZ",
        bg: "#00000086",
        br: "transparent",
        w: "100px",
        h: "50px",
      },
    ],
  ];
};
